export const ADD_POINT = 'ADD_POINT';
export const REMOVE_POINT = 'REMOVE_POINT';
export const SET_DEFAULT_RACE_BONUS = 'SET_DEFAULT_RACE';
export const SET_DEFAULT_THEME_BONUS = 'SET_DEFAULT_THEME_BONUS';