export const UPDATE_ABILITY_SCORE = 'UPDATE_ABILITY_SCORE';
export const ADD_POINT = 'ADD_POINT';
export const REMOVE_POINT = 'REMOVE_POINT';
export const SET_DEFAULT_RACIAL = 'SET_DEFAULT_RACIAL';
export const SET_DEFAULT_THEME = 'SET_DEFAULT_THEME';