export const UPDATE_KINETIC_ARMOR = 'UPDATE_KINETIC_ARMOR';
export const UPDATE_ENERGY_ARMOR = 'UPDATE_ENERGY_ARMOR';
export const UPDATE_MISC_ARMOR = 'UPDATE_MISC_ARMOR';
export const UPDATE_DAMAGE_REDUCTION = 'UPDATE_DAMAGE_REDUCTION';
export const UPDATE_RESISTANCES = 'UPDATE_RESISTANCES';
