export const CHANGE_RACE = 'CHANGE_RACE';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_CLASS = 'CHANGE_CLASS';
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_GENDER = 'CHANGE_GENDER';
export const CHANGE_HOME_WORLD = 'CHANGE_HOME_WORLD';
export const CHANGE_ALIGNMENT = 'CHANGE_ALIGNMENT';
export const CHANGE_DEITY = 'CHANGE_DEITY';