export const UPDATE_CURRENT_STAMINA = 'UPDATE_CURRENT_STAMINA';
export const UPDATE_CURRENT_HP = 'UPDATE_CURRENT_HP';
export const UPDATE_CURRENT_RESOLVE = 'UPDATE_CURRENT_RESOLVE';
export const UPDATE_HEALTH_CLASS_CONTRIBUTIONS = 'UPDATE_HEALTH_CLASS_CONTRIBUTIONS';
export const UPDATE_STAMINA_CONSTITUTION_CONTRIBUTION = 'UPDATE_STAMINA_CONSTITUTION_CONTRIBUTION';
export const UPDATE_KEY_ABILITY_CONTRIBUTION = 'UPDATE_KEY_ABILITY_CONTRIBUTION';