export const UPDATE_RANKS_IN_SKILL = 'UPDATE_RANKS_IN_SKILL';
export const UPDATE_MISC_MODIFIER_FOR_SKILL = 'UPDATE_MISC_MODIFIER_FOR_SKILL';
export const UPDATE_PROFESSION_NAME = 'UPDATE_PROFESSION_NAME';
export const UPDATE_PROFESSION_ABILITY = 'UPDATE_PROFESSION_ABILITY';
export const UPDATE_EXTRA_CLASS_SKILL = 'UPDATE_EXTRA_CLASS_SKILL';