export const ADD_SPELL = 'ADD_SPELL';
export const REMOVE_SPELL = 'REMOVE_SPELL';
export const UPDATE_SPELLS_PER_DAY = 'UPDATE_SPELLS_PER_DAY';
export const UPDATE_SPELLS_SLOTS_USED = 'UPDATE_SPELLS_SLOTS_USED';